it('successful signup', function(){
    cy.visit('/login')
    cy.get('[data-qa="signup-name"]').clear().type('Ana')
    cy.get('[data-qa="signup-email"]').clear().type('ana.qa.tester@outlook.com')
    cy.get('[data-qa="signup-button"]').click()
    cy.url().should('eq', 'https://www.automationexercise.com/signup')
    cy.get('#id_gender2').check()
    cy.get('[data-qa="name"]').should('have.value', 'Ana')
    cy.get('[data-qa="email"]').should('have.value', 'ana.qa.tester@outlook.com').and('be.disabled')
    cy.get('[data-qa="password"]').clear().type('1234567')
    cy.get('[data-qa="days"]').select('11')
    cy.get('[data-qa="months"]').select('5')
    cy.get('[data-qa="years"]').select('2000')
    cy.get('#newsletter').check()
    cy.get('#optin').check()
    cy.get('[data-qa="first_name"]').type('Ana')
    cy.get('[data-qa="last_name"]').type('Tester')
    cy.get('[data-qa="company"]').type('IT')
    cy.get('[data-qa="address"]').type('Address')
    cy.get('[data-qa="address2"]').type('Address 2')
    cy.get('[data-qa="country"]').select('United States')
    cy.get('[data-qa="state"]').type('California')
    cy.get('[data-qa="city"]').type('Los Angeles')
    cy.get('[data-qa="zipcode"]').type('12345')
    cy.get('[data-qa="mobile_number"]').type('123456789')
    cy.get('[data-qa="create-account"]').click()
    cy.url().should('eq', 'https://www.automationexercise.com/account_created')
    cy.get('[data-qa="account-created"]').should('have.text', 'Account Created!')
    cy.get('[data-qa="continue-button"]').click()
    cy.url().should('eq', 'https://www.automationexercise.com/')    
})

it.only('user cannot sign up with existing email', function(){
    cy.visit('/login')
    cy.get('[data-qa="signup-name"]').clear().type('Ana')
    cy.get('[data-qa="signup-email"]').clear().type('ana.qa.tester@outlook.com')
    cy.get('[data-qa="signup-button"]').click()
    cy.get('[action="/signup"] p').should('have.text', 'Email Address already exist!')
    cy.url().should('eq', 'https://www.automationexercise.com/signup')
    
})


